version: '3'
services:
  price-scraper-db:
    build:
      context: ./postgres-docker
    ports:
      - "5432:5432"
    networks:
      - my-network

  price-scraper-api:
    build:
      context: .
    ports:
      - "8080:8080"
    depends_on:
      - price-scraper-db
    networks:
      - my-network

networks:
  my-network:
