version: '3'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qwer
      POSTGRES_DB: price_scraper
    volumes:
      - type: volume
        source: psql_data
        target: /var/lib/postgresql/data
    ports:
      - "5433:5432"
  api:
    build: .
    ports:
      - "8081:8080"
    depends_on:
      - db
volumes:
  psql_data:
networks:
  app:
